
ALTER TABLE t_p28211681_photo_secure_web.folder_short_links
ADD COLUMN IF NOT EXISTS bg_theme VARCHAR(10) DEFAULT 'light',
ADD COLUMN IF NOT EXISTS bg_color VARCHAR(20) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bg_image_url TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS text_color VARCHAR(20) DEFAULT NULL;
